apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mysqldump
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mysqldump
            image: zreigz/mysql-dump
            env:
              - name: DB_NAME
                value: mydatabase
              - name: DB_HOST
                value: galera-ss
              - name: DB_USER
                value: myuser
              - name: DB_PASS
                value: myuserpassword
            volumeMounts:
              - mountPath: /mysqldump
                name: mysqldump
          volumes:
            - name: mysqldump
              hostPath:
                path: /tmp/mysqldump
          restartPolicy: OnFailure
