FROM php:7.0-apache
MAINTAINER Lukasz Zajaczkowski "zreigz@gmail.com"
COPY proxy.php /var/www/html/proxy.php
COPY post.php /var/www/html/post.php
COPY index.html /var/www/html/index.html

EXPOSE  80



